apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mongodb-doorman
  annotations:
    fluxcd.io/automated: "false"
  namespace: corda-svcs-ns
spec:
  replicaCount: 1
  replicas: 1
  releaseName: mongodb-doorman
  chart:
    path: platforms/r3-corda/charts/mongodb
    git: https://github.com/Dabami/baf-cross.git
    ref: corda-svcs
  values:
    nodeName: mongodb-doorman
    metadata:
      namespace: corda-svcs-ns
    image:
      containerName: mongo:3.6.6
      imagePullSecret: regcred
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    storage:
      memory: 512Mi
      name: longhornstorageclass
      mountPath: /data/db
      volname: hostvol
    vault:
      address: http://172.28.3.115:8200
      role: vault-role
      authpath: cordadoorman
      secretprefix: doorman/data/credentials/mongodb
      serviceaccountname: vault-auth
      certsecretprefix: doorman/data/certs
    service:
      tcp:
          port: 27017
          targetPort: 27017
      type: NodePort
      annotations: {}
    deployment:
      annotations: {}
    pvc:
      annotations: {}
    mongodb:
      username: doorman
    cluster:
      enabled: false
