apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: operatorb-initial-registration
  annotations:
    fluxcd.io/automated: "false"
  namespace: operatorb-ns
spec:
  releaseName: operatorb-initial-registration
  chart:
    path: platforms/r3-corda/charts/node-initial-registration
    git: git@github.com:Mike-no/blockchain-automation-framework-1.git
    ref: operator-b
  values:
    nodeName: operatorb
    replicas: 1
    metadata:
      namespace: operatorb-ns  
    image:
      containerName: index.docker.io/hyperledgerlabs/corda:4.7-linuxkit
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: 192.168.49.2
      networkmapCertAlias: 192.168.49.2
    nodeConf:
      p2p:
        url: operatorb.operatorb-ns
        port: 10002
      ambassadorAddress: operatorb.test.corda.blockchaincloudpoc.com:15020
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=OperatorB,OU=Zurich,L=47.38/8.54/Zurich,C=CH #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
       
      detectPublicIp: false
      database:
        exportHibernateJMXStatistics: false
      dbUrl: operatorbdb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://operatorbdb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: http://192.168.49.2:30040
      doormanURL: http://192.168.49.2:30030
      compatibilityZoneURL:
      jarVersion: 4.7
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: operatorboperations
          permissions: [ALL]

    volume:
      baseDir: /base/corda
    resources:
      limits: "512Mi"
      requests: "512Mi"
    
    service:
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
      rpcadmin:
        port: 10005

    vault:
      address: http://host.minikube.internal:8200
      role: vault-role
      authpath: cordaoperatorb
      serviceaccountname: vault-auth
      dbsecretprefix: operatorb/data/credentials/database
      rpcusersecretprefix: operatorb/data/credentials/rpcusers
      tokensecretprefix: operatorb/data/credentials/vaultroottoken
      keystoresecretprefix: operatorb/data/credentials/keystore
      certsecretprefix: operatorb/data/certs
        
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
