apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: notary
  annotations:
    fluxcd.io/automated: "false"
  namespace: corda-svcs-ns
spec:
  releaseName: notary
  chart:
    path: platforms/r3-corda/charts/notary
    git: https://github.com/Dabami/baf-cross.git
    ref: corda-svcs
  values:
    nodeName: notary
    replicas: 1
    metadata:
      namespace: corda-svcs-ns
    image:
      containerName: index.docker.io/hyperledgerlabs/corda:4.7-linuxkit
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: 172.28.3.178
      networkmapCertAlias: 172.28.3.178
    nodeConf:
      p2p:
        url: notary.corda-svcs-ns
        port: 10002
      ambassadorAddress: notary.test.corda.blockchaincloudpoc.com:15010
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Notary,OU=Notary,L=London,C=GB #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
            
      notary:
        validating: True
        serviceLegalName: O=Notary Service,OU=Notary,L=London,C=GB
       
      detectPublicIp: false
      database:
        exportHibernateJMXStatistics: false
      dbUrl: notarydb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://notarydb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: http://172.28.3.178:30040
      doormanURL: http://172.28.3.178:30030
      compatibilityZoneURL:
      jarVersion: 4.7
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx1024m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: notaryoperations
          permissions: [ALL]

    cordapps:
      getcordapps: false

    volume:
      baseDir: /base/corda
    resources:
      limits: "2Gi"
      requests: "2Gi" 
    pvc:
      name: notary-pvc
      annotations: {}
      memory: 512Mi
      storageClassName: longhornstorageclass

    service:
      name: notary
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
        targetPort: 10003 
      rpcadmin:
        port: 10005
        targetPort: 10005
         
    deployment:
      annotations: {}
    vault:
      address: http://172.28.3.115:8200/
      role: vault-role
      authpath: cordanotary
      serviceaccountname: vault-auth
      dbsecretprefix: notary/data/credentials/database
      rpcusersecretprefix: notary/data/credentials/rpcusers
      tokensecretprefix: notary/data/credentials/vaultroottoken
      keystoresecretprefix: notary/data/credentials/keystore
      certsecretprefix: notary/data/certs
      networkmapsecretprefix: notary/data/credentials/networkmappassword
      cordappsreposecretprefix: notary/data/credentials/cordapps

          
    healthcheck:
      readinesscheckinterval: 20
      readinessthreshold: 20
    ambassador:
      component_name: notary
      external_url_suffix: test.corda.blockchaincloudpoc.com
      p2p_ambassador: 15010
