apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: operatora-initial-registration
  annotations:
    fluxcd.io/automated: "false"
  namespace: operatora-ns
spec:
  releaseName: operatora-initial-registration
  chart:
    path: platforms/r3-corda/charts/node-initial-registration
    git: https://github.com/Dabami/baf-cross.git
    ref: operator-a
  values:
    nodeName: operatora
    replicas: 1
    metadata:
      namespace: operatora-ns  
    image:
      containerName: index.docker.io/hyperledgerlabs/corda:4.7-linuxkit
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: 172.28.3.178
      networkmapCertAlias: 172.28.3.178
    nodeConf:
      p2p:
        url: operatora.operatora-ns
        port: 10002
      ambassadorAddress: operatora.test.corda.blockchaincloudpoc.com:15020
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: CN=OperatorA,OU=DLT,O=DLT,L=51.50/-0.11/London,C=GB #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
       
      detectPublicIp: false
      database:
        exportHibernateJMXStatistics: false
      dbUrl: operatoradb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://operatoradb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: http://172.28.3.178:30040
      doormanURL: http://172.28.3.178:30030
      compatibilityZoneURL:
      jarVersion: 4.7
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: operatoraoperations
          permissions: [ALL]

    volume:
      baseDir: /base/corda
    resources:
      limits: "512Mi"
      requests: "512Mi"
    
    service:
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
      rpcadmin:
        port: 10005

    vault:
      address: http://172.28.3.115:8200
      role: vault-role
      authpath: cordaoperatora
      serviceaccountname: vault-auth
      dbsecretprefix: operatora/data/credentials/database
      rpcusersecretprefix: operatora/data/credentials/rpcusers
      tokensecretprefix: operatora/data/credentials/vaultroottoken
      keystoresecretprefix: operatora/data/credentials/keystore
      certsecretprefix: operatora/data/certs
        
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
